            ;; rtc.inc
            ;;
            ;; partner mm58167 rtc constants
            ;;
            ;; 2026-06-13   tstih

            .equ    RTC_PORT_SEC,            0xa2
            .equ    RTC_PORT_MIN,            0xa3
            .equ    RTC_PORT_HOUR,           0xa4
            .equ    RTC_PORT_MDAY,           0xa6
            .equ    RTC_PORT_MON,            0xa7
            .equ    RTC_PORT_YEAR,           0xa9
            .equ    RTC_TIME_SIZE,           6
